name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on: push

permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: android-common
      tagName: android15-6.6
    steps:
      - name: check mingw version
        run: gcc --version
        
      - name: git clone
        shell: cmd
        run: git clone --recurse-submodules git clone https://android.googlesource.com/kernel/common && cd common && git checkout ${{ env.tagName }}
        

      # - name: Archive Release
      #   uses: thedoctor0/zip-release@master
      #   with:
      #     type: 'zip'
      #     directory: "portaudio/cmake-build/${{ env.cmakeInstallationPath }}"
      #     filename: "${{ env.mingwTargetZip }}"
          
      # - name: Release prebuilt
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "portaudio/cmake-build/${{ env.cmakeInstallationPath }}/${{ env.mingwTargetZip }}"
      #     allowUpdates: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
